// export const data = 


  // dataRelations: [
  //   {
  //     name: "Distributer",
  //     children: [
  //       {
  //         name: "Seller 1",
  //         children: [
  //           { name: "A1", value: 100 },
  //           { name: "A2", value: 80 },
  //           { name: "A3", value: 60 },
  //           { name: "A4", value: 70 },
  //           { name: "A5", value: 50 },
  //           { name: "A6", value: 40 },
  //           { name: "A7", value: 30 },
  //           { name: "A8", value: 20 },
  //           { name: "A9", value: 10 },
  //           { name: "A10", value: 60 },
  //         ],
  //       },
  //       {
  //         name: "Seller 2",
  //         children: [
  //           { name: "B1", value: 135 },
  //           { name: "B2", value: 165 },
  //           { name: "B3", value: 115 },
  //           { name: "B4", value: 178 },
  //           { name: "B5", value: 187 },
  //           { name: "B6", value: 152 },
  //           { name: "B7", value: 139 },
  //           { name: "B8", value: 120 },
  //           { name: "B9", value: 35 },
  //           { name: "B10", value: 98 },
  //         ],
  //       },
  //       {
  //         name: "Seller 3",
  //         children: [
  //           { name: "c1", value: 50 },
  //           { name: "c2", value: 135 },
  //           { name: "c3", value: 195 },
  //           { name: "c4", value: 250 },
  //           { name: "c5", value: 260 },
  //           { name: "c6", value: 270 },
  //           { name: "c7", value: 280 },
  //           { name: "c8", value: 135 },
  //           { name: "c9", value: 120 },
  //           { name: "c10", value: 100 },
  //         ],
  //       },
  //     ],
  //   },
  // ],

  // dataTableChart: [
  //   {
  //     name: "Positive",
  //     order: 501.9,
  //     rate: "49.9%",
  //     reviewText: "Positive: 49.9%",
  //   },
  //   {
  //     name: "Negative",
  //     order: 301.9,
  //     rate: "30%",
  //     reviewText: "Negative: 30%",
  //   },
  //   {
  //     name: "Neutral",
  //     order: 201.1,
  //     rate: "20%",
  //     reviewText: "Neutral: 20%",
  //   },
  // ],
  // dataTableBars: [
  //   {
  //     name: "Metal",
  //     day1: 40,
  //     day2: 30,
  //     day3: 27,
  //     day4: 50,
  //     day5: 60,
  //     day6: 40,
  //     day7: 50,
  //     day8: 50,
  //     day9: 40,
  //     day10: 54,
  //   },
  //   {
  //     name: "Plastic",
  //     day1:  55,         
  //     day2: 78,
  //     day3: 33,
  //     day4: 73,
  //     day5: 55,
  //     day6: 33,
  //     day7: 33,
  //     day8: 50,
  //     day9: 34,
  //     day10: 25,
  //   },
  //   {
  //     name: "Glass",
  //     day1: 60,
  //     day2: 69,
  //     day3: 45,
  //     day4: 22,
  //     day5: 42,
  //     day6: 14,
  //     day7: 22,
  //     day8: 22,
  //     day9: 32,
  //     day10: 41,
  //   },
  // ],